import{a as v,S,i as g}from"./assets/vendor-u8rapaCG.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&r(d)}).observe(document,{childList:!0,subtree:!0});function l(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=l(t);fetch(t.href,s)}})();const L="46054358-74185f2755c78a9980c41a2df",q="https://pixabay.com/api/";async function m(e,o=1,l=15){try{return(await v.get(q,{params:{key:L,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:l}})).data}catch(r){throw console.error(r),new Error("Error fetching images.")}}let u=null;function b(e){const o=document.querySelector(".gallery"),l=e.map(r=>`
        <div class="gallery-item">
            <div class="photo-card">
                <a href="${r.largeImageURL}" class="gallery-link">
                    <img width="360" height="152" src="${r.webformatURL}" class="photo-card-img" alt="${r.tags}" loading="lazy"/>
                </a>
                <div class="info">
                    <p><b>Likes</b> ${r.likes}</p>
                    <p><b>Views</b> ${r.views}</p>
                    <p><b>Comments</b> ${r.comments}</p>
                    <p><b>Downloads</b> ${r.downloads}</p>
                </div>
            </div>
        </div>
    `).join("");o.insertAdjacentHTML("beforeend",l),u?u.refresh():u=new S(".gallery a")}function y(){const e=document.querySelector(".gallery");e.innerHTML=""}function C(){g.warning({message:"Sorry, there are no images matching <br>your search query. Please try again!",position:"topRight",backgroundColor:"red",class:"toast-center",titleColor:"white",title:"ⓧ",titleSize:"22px",icon:"",messageColor:"white",theme:"dark"})}function p(e){g.error({message:e,position:"topRight",backgroundColor:"red",class:"toast-center",titleColor:"white",title:"ⓧ",titleSize:"22px",icon:"",messageColor:"white",theme:"dark"})}function E(){g.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"blue",class:"toast-center",messageColor:"white"})}const w=document.querySelector("#search-form"),c=w.querySelector("input"),a=document.querySelector(".loader"),n=document.querySelector(".load-more");let i=1,h="",f=0;n.style.display="none";w.addEventListener("submit",async e=>{e.preventDefault();const o=c.value.trim();if(!o||o===""){y(),n.style.display="none",p("The search field cannot be empty!"),c.value="";return}a.style.display="block",n.style.display="none",i=1,h=o;try{const l=await m(h,i);a.style.display="none",y(),c.value="",l.hits.length===0?C():(b(l.hits),f=l.totalHits,i*15<f&&(n.style.display="block"))}catch{a.style.display="none",y(),p("The request failed. Please try again later."),c.value=""}});n.addEventListener("click",async()=>{i+=1,a.style.display="block";try{const e=await m(h,i);a.style.display="none",e.hits.length===0||i*15>=f?(n.style.display="none",E()):(b(e.hits),k())}catch{a.style.display="none",p("Failed to load more images. Please try again later.")}});function k(){const o=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
