import{a as L,S as q,i as g}from"./assets/vendor-u8rapaCG.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const l of t)if(l.type==="childList")for(const u of l.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function s(t){const l={};return t.integrity&&(l.integrity=t.integrity),t.referrerPolicy&&(l.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?l.credentials="include":t.crossOrigin==="anonymous"?l.credentials="omit":l.credentials="same-origin",l}function r(t){if(t.ep)return;t.ep=!0;const l=s(t);fetch(t.href,l)}})();const C="46054358-74185f2755c78a9980c41a2df",E="https://pixabay.com/api/";async function b(e,o=1,s=15){try{return(await L.get(E,{params:{key:C,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:s}})).data}catch(r){throw console.error(r),new Error("Error fetching images.")}}let y=null;function w(e){const o=document.querySelector(".gallery"),s=e.map(r=>`
        <div class="gallery-item">
            <div class="photo-card">
                <a href="${r.largeImageURL}" class="gallery-link">
                    <img width="360" height="152" src="${r.webformatURL}" class="photo-card-img" alt="${r.tags}" loading="lazy"/>
                </a>
                <div class="info">
                    <p><b>Likes</b> ${r.likes}</p>
                    <p><b>Views</b> ${r.views}</p>
                    <p><b>Comments</b> ${r.comments}</p>
                    <p><b>Downloads</b> ${r.downloads}</p>
                </div>
            </div>
        </div>
    `).join("");o.insertAdjacentHTML("beforeend",s),y?y.refresh():y=new q(".gallery a")}function h(){const e=document.querySelector(".gallery");e.innerHTML=""}function k(){g.warning({message:"Sorry, there are no images matching <br>your search query. Please try again!",position:"topRight",backgroundColor:"red",class:"toast-center",titleColor:"white",title:"ⓧ",titleSize:"22px",icon:"",messageColor:"white",theme:"dark"})}function p(e){g.error({message:e,position:"topRight",backgroundColor:"red",class:"toast-center",titleColor:"white",title:"ⓧ",titleSize:"22px",icon:"",messageColor:"white",theme:"dark"})}function S(){g.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"blue",class:"toast-center",messageColor:"white"})}const v=document.querySelector("#search-form"),m=v.querySelector("input"),i=document.querySelector(".loader"),a=document.querySelector(".load-more");let c=1,f="",d=0,n=0;a.style.display="none";i.style.display="none";function R(){c=1,n=0,d=0,h(),a.style.display="none",a.disabled=!1}v.addEventListener("submit",async e=>{e.preventDefault();const o=m.value.trim();if(!o||o===""){h(),m.value="",a.style.display="none",p("The search field cannot be empty!");return}R(),f=o,i.style.display="block";try{const s=await b(f,c);i.style.display="none",s.hits.length===0?k():(w(s.hits),d=s.totalHits,n+=s.hits.length,n<d?a.style.display="block":S())}catch{i.style.display="none",h(),p("The request failed. Please try again later.")}});a.addEventListener("click",async()=>{c+=1,i.style.display="block",a.disabled=!0;try{const e=await b(f,c);e.hits.length>0&&(w(e.hits),n+=e.hits.length,P(),n>=d?(a.style.display="none",S()):a.disabled=!1)}catch{i.style.display="none",p("Failed to load more images. Please try again later."),a.disabled=!1}finally{i.style.display="none"}});function P(){const o=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
